// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esfcukvynjbkocehacew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZmN1a3Z5bmpia29jZWhhY2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjgwNDksImV4cCI6MjA1NzM0NDA0OX0.wszHxnnN_AbR75rCmT-iOKFKblPvV1T158PN585PoOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);